### ISSUE TITLE
Package in Exherbo app-misc not showing

### ISSUE THREAD

**Issue by jarun** [repology/repology-updater#960]
A user brought to my notice that `nnn` is available in Exherbo under the app-misc category:

https://git.exherbo.org/summer/packages/app-misc/nnn/index.html

However, it doesn't show in the repology badge: https://repology.org/badge/vertical-allrepos/nnn.svg

Can you please fix this?

**Comment by AMDmi3** [comment]
You may want to refresh the repository list at https://github.com/repology/repology-updater/blob/master/repos.d/exherbo.yaml

**Comment by jarun** [comment]
> You may want to refresh

How do I do that?

**Comment by jarun** [comment]
Do you mean some sections like `app-misc` are missing

**Comment by jarun** [comment]
OK, got the package and the dev. Thanks for the pointer.

**Comment by AMDmi3** [comment]
As I understand exherbo is a combination of a bunch of repositories. Currently, repos listed on https://git.exherbo.org/ are used. nnn comes from https://gitlab.exherbo.org/DanySpin97/danyspin97-exheres not listed anywhere. So we need an actual listing of repositories Exherbo consists of, and Repology config needs to be updated with it.

**Comment by jarun** [comment]
Raised PR #962.

**Comment by DanySpin97** [comment]
Hi there. I am the mantainer of nnn package in Exherbo.

> As I understand exherbo is a combination of a bunch of repositories.

Yup, there are 2 types of repositories: official ones (both Exherbo repositories and developer's personal ones) and unofficial ones. The official ones are already included by repology.

About the unofficial ones; they are (strictly) reviewed by Exherbo devs and then added to [this folder](https://gitlab.exherbo.org/exherbo-misc/infra-scripts/tree/master/playboy/exherbo-unofficial/config/repositories). They do not contain duplicate packages.

The format is the same, but the repositories can be anywhere; almost all of them are on gitlab.exheres.org but some are on github.com too. In the next days I will have a look at the way repology parse [exherbo.yaml](https://github.com/repology/repology-updater/blob/master/repos.d/exherbo.yaml) and add the unofficial ones too.

**Comment by AMDmi3** [comment]
Isn't there a complete merged information on all supported packages? Maybe somewhere around https://git.exherbo.org/summer/packages/app-misc/nnn/index.html?

There are two problems with current approach:
- We have to maintain a list of Exherbo repositories in Repology, which is duplication of something already done in exherbo itself, and will always introduce lag and lead to issues like this one.
- The data Repology parses from Exherbo is incomplete, see warning at https://repology.org/repository/exherbo. In fact, we are only able to parse repository file structure which is enough to extract package names and versions, and also get maintainer information from repository metadata, but that's it and it no longer corresponds to our quality standards, as at least homepage information is crucial.

**Comment by jarun** [comment]
@AMDmi3 strangely I see an issue with listing packages on openSUSE.

The package `Buku` is available in the openSUSE repos: https://software.opensuse.org/package/python3-buku

However, I don't see openSUSE as a packager here: https://repology.org/project/buku/versions

**Comment by AMDmi3** [comment]
https://repology.org/projects/?search=buku&inrepo=opensuse_leap_15_1

**Comment by jarun** [comment]
It's showing as python:buku

**Comment by AMDmi3** [comment]
Yes

**Comment by jarun** [comment]
Adding @dilawar.

**Comment by AMDmi3** [comment]
Merged

**Comment by jarun** [comment]
Is there an automatic way? The same thing happens with project pdd (python:pdd) which is available in openSUSE Tumbleweed.

**Comment by AMDmi3** [comment]
There isn't.

**Comment by jarun** [comment]
@DanySpin97 any update on this?

**Comment by jarun** [comment]
@DanySpin97 any update here?

**Comment by DanySpin97** [comment]
Sorry for the delay.

> I guess it shouldn't be too hard to teach it to output some machine readable dump of all packages which Repology could use.

Yea, it is doable. I am starting working on it right now. In the end there will be a json file that can be parsed by repology with all the metadata needed.

**Comment by jarun** [comment]
That's great!

**Comment by jarun** [comment]
@DanySpin97 is this working now?

**Comment by filko** [comment]
Packages are now exported at `https://git.exherbo.org/summer/packages.json`, updated daily.

**Comment by jarun** [comment]
:+1: Thank you!

**Comment by jarun** [comment]
@AMDmi3 would the original issue get resolved now?

**Comment by AMDmi3** [comment]
Looks almost good.
@filko could you please add maintainer (to avoid regression compared to older exherbo support implementation) and subrepository name (so it's possible to add links to exheres directly) fields?

**Comment by jarun** [comment]
@filko any update on this? Still don't see `nnn` listed as available in Exherbo.

While I poked @AMDmi3 because of a user request, I do see the value of a this informative service that shows where a package is at which version. I donno about users, it helps me poke a maintainer from time to time when I see a package not updated for long so the users of that distro can get the latest package faster.

Given the number of ditros Linux has, this is all the more relevant. Kindly see if this can be prioritized.

**Comment by AMDmi3** [comment]
@filko ping. This is very close to being usable, only two small changes remaining.

**Comment by tombriden** [comment]
Hi, the json now includes the `repository` key but still not `maintainers` as exherbo doesn't have specific package maintainers, it's a group effort to manage package changes as needed. Can I suggest just having a fallback value of something like `#exherbo on Freenode`?

**Comment by AMDmi3** [comment]
In the git repo Repology currently uses there are `<repo>/metadata/about.conf` files some of which contain `owner` entry:

```
dev_alip/metadata/about.conf:owner = Ali Polatel <alip@exherbo.org>
dev_arkanoid/metadata/about.conf:owner = Anders Ossowicki <arkanoid@exherbo.org>
dev_berniyh/metadata/about.conf:owner = Bernd Steinhauser <berniyh@exherbo.org>
dev_ciaranm/metadata/about.conf:owner = Ciaran McCreesh <ciaran.mccresh@googlemail.com>
dev_cogitri/metadata/about.conf:owner = Rasmus Thomsen <cogitri@exherbo.org>
dev_compnerd/metadata/about.conf:owner = Saleem Abdulrasool <compnerd@exherbo.org>
dev_dleverton/metadata/about.conf:owner = David Leverton <dleverton@exherbo.org>
dev_ferdy/metadata/about.conf:owner = Fernando J. Pereda <ferdy@exherbo.org>
dev_heirecka/metadata/about.conf:owner = Heiko Becker <heirecka@exherbo.org>
dev_ingmar/metadata/about.conf:owner = Ingmar Vanhassel <ingmar@exherbo.org>
dev_keruspe/metadata/about.conf:owner = Marc-Antoine Perennou <keruspe@exherbo.org>
dev_kimrhh/metadata/about.conf:owner = Kim Højgaard-Hansen <kimrhh@exherbo.org>
dev_marv/metadata/about.conf:owner = Marvin Schmidt <marv@exherbo.org>
dev_mixi/metadata/about.conf:owner = Johannes Nixdorf <mixi@exherbo.org>
dev_moben/metadata/about.conf:owner = Benedikt Morbach <moben@exherbo.org>
dev_mrothe/metadata/about.conf:owner = mrothe <mrothe@exherbo.org>
dev_olesalscheider/metadata/about.conf:owner = Niels Ole Salscheider <olesalscheider@exherbo.org>
dev_philantrop/metadata/about.conf:owner = Wulf C. Krueger <philantrop@exherbo.org>
dev_pioto/metadata/about.conf:owner = Mike Kelly <pioto@exherbo.org>
dev_pipping/metadata/about.conf:owner = Elias Pipping <pipping@exherbo.org>
dev_pyro/metadata/about.conf:owner = Thomas Witt <pyromaniac@exherbo.org>
dev_rbrown/metadata/about.conf:owner = Richard Brown <rbrown@exherbo.org>
dev_replica/metadata/about.conf:owner = Sterling X. Winter <replica@exherbo.org>
dev_sejo/metadata/about.conf:owner = Jochen Maes <sejo@exherbo.org>
dev_sepek/metadata/about.conf:owner = Paul Seidler <sepek@exherbo.org>
dev_somasis/metadata/about.conf:owner = Kylie McClain <somasis@exherbo.org>
dev_spbecker/metadata/about.conf:owner = Stephen P. Becker <spbecker@exherbo.org>
dev_spoonb/metadata/about.conf:owner = Brett Witherspoon <spoonb@exherbo.org>
dev_tanderson/metadata/about.conf:owner = Thomas Anderson <gentoofan23@gentoo.org>
dev_tridactyla/metadata/about.conf:owner = Michael Forney <mforney@mforney.org>
dev_woutershep/metadata/about.conf:owner = Wouter van Kesteren <woutershep@gmail.com>
dev_zlin/metadata/about.conf:owner = Bo Ørsted Andresen <zlin@exherbo.org>
```
Should these not be considered as maintainers? These may not be maintainers in the common sense, but still useful for people to distinguish a set of packages they are responsible for, and some of these people may already rely on this, so losing this info would be a regression. If you're sure nobody relies on that, we can just switch to json.

> Can I suggest just having a fallback value of something like #exherbo on Freenode?

There's no point having a pseudo maintainer for a whole repository, so if owners is not deemed useful we can just not set any maintainer.

**Comment by tombriden** [comment]
Those owners are for those specific repos, rather than the packages within. While they may have created the initial exheres for a package there's no guarantee they are handling any future version bumps or changes. Indeed, I've been doing version bumps in  a few of those repos but also wouldn't necessarily want to be considered the maintainer of them going forward. 
One of the main principles of exherbo is for the users to take part in development. So, if you see a package needs updating then you'd be encouraged to submit a MR for it rather than asking for someone else to do it.

Given than, I think it's fine to lose that info going forward and just use the json as it is without having maintainers defined.

Thanks!

**Comment by AMDmi3** [comment]
Done. For the record, `nnn` is now [visible](https://repology.org/project/nnn/versions#exherbo) in Exherbo.

Note that there's some broken exheres files in some repositories which lead to broken data: https://repology.org/log/4227649

**Comment by jarun** [comment]
@tombriden lloks like the package is not listed anymore: https://git.exherbo.org/summer/packages/app-misc/nnn/index.html

Can you please take a look.

**Comment by heirecka** [comment]
That is so far intentional as the repository containing nnn was a third-party one and its owner moved on to other things (https://gitlab.exherbo.org/exherbo-misc/graveyard/-/merge_requests/76). This happens from time to time with third party repos. If anybody interested in nnn turns up, we will re-import it, including the history from that repo.

**Comment by jarun** [comment]
Thanks for the update. I don't use Exherbo so no issues personally.
